config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
      <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
      <% end %>
  </script>

<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>

<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "AirBcb", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class:"navbar-form navbar-left", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
        </div>

      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-small btn-form">
            <%= link_to "Become a host", new_room_path, style: "color: white; text-decorations: none;" %>
          </button>

        </li>

        <% if !user_signed_in? %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Signup", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
                <%= current_user.fullname %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Your Listings", rooms_path %></li>
              <li><%= link_to "List Your Space", new_room_path %></li>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <li><%= link_to "Your Trips", your_trips_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Edit your profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>

        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>