config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :authenticate_user!

  def create
    room = Room.find(params[:room_id])

    if current_user == room.user
      flash[:alert] = "You cannot book your own property!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = (end_date - start_date).to_i + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price
      @reservation.total = room.price * days
      @reservation.save

      flash[:notice] = "Booked Successfully!"
    end
    redirect_to room
  end

  def destroy

  end

  def your_trips
    @trips = current_user.reservations.order(stat_date: :asc)
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end
end

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span><i class="fa fa-bolt" style="color: #ffb400"></i> $<%= @room.price %></span>
    <span class="pull-right">Per Night</span>
  </div>
  <div class="panel-body">
    <%= form_for([@room, @room.reservations.new]) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>Check In</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>Check Out</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "End Date", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
          <tr>
            <td>Price</td>
            <td class="text-right">$<%= @room.price %></td>
          </tr>
          <tr>
            <td>Night(s)</td>
            <td class="text-right">x <span id="reservation_nights"></span></td>
          </tr>
          <tr>
            <td class="total">Total</td>
            <td class="text-right">$<span id="reservation_total"></span></td>
          </tr>
          </tbody>
        </table>
      </div>

      <br/>

      <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
    <% end %>
  </div>
</div>






<script>

    function checkDate(date) {
        dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
        return [$.inArray(dmy, unavailableDates) == -1];
    }

    $(function() {

        unavailableDates = [];

        $.ajax({
            url: '<%= preload_room_path(@room) %>',
            dateType: 'json',
            success: function(data) {

                $.each(data, function(arrID, arrValue) {
                    for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
                    }
                });

                $('#reservation_start_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: checkDate,
                    onSelect: function(selected) {
                        $('#reservation_end_date').datepicker("option", "minDate", selected);
                        $('#reservation_end_date').attr("disabled", false);

                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var nights = (end_date - start_date)/1000/60/60/24 + 1;

                        var input = {
                            'start_date': start_date,
                            'end_date': end_date
                        }

                        $.ajax({
                            url: '<%= preview_room_path(@room) %>',
                            data: input,
                            success: function(data) {

                                if(data.conflict) {
                                    $('#message').text("These dates are not available.");
                                    $('#preview').hide();
                                    $('#btn_book').attr('disabled', true);
                                } else {
                                    $('#message').text("");
                                    $('#preview').show();
                                    $('#btn_book').attr('disabled', false);

                                    var total = nights * <%= @room.price %>;
                                        $('#reservation_nights').text(nights);
                                        $('#reservation_total').text(total);
                                }
                            }
                        });

                    }
                });

                $('#reservation_end_date').datepicker({
                    dateFormat: 'dd-mm-yy',
                    minDate: 0,
                    maxDate: '3m',
                    beforeShowDay: checkDate,
                    onSelect: function(selected) {
                        $('#reservation_start_date').datepicker("option", "maxDate", selected);

                        var start_date = $('#reservation_start_date').datepicker('getDate');
                        var end_date = $('#reservation_end_date').datepicker('getDate');
                        var nights = (end_date - start_date)/1000/60/60/24 + 1;

                        var input = {
                            'start_date': start_date,
                            'end_date': end_date
                        }

                        $.ajax({
                            url: '<%= preview_room_path(@room) %>',
                            data: input,
                            success: function(data) {

                                if(data.conflict) {
                                    $('#message').text("These dates are not available.");
                                    $('#preview').hide();
                                    $('#btn_book').attr('disabled', true);
                                } else {
                                    $('#message').text("");
                                    $('#preview').show();
                                    $('#btn_book').attr('disabled', false);

                                    var total = nights * <%= @room.price %>
                                        $('#reservation_nights').text(nights);
                                    $('#reservation_total').text(total);
                                }
                            }
                        });
                    }
                });
            }
        });



    });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Reservations
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
          <% room.reservations.each do |reservation| %>
            <div class="row">
              <div class="col-md-2">
                <%= reservation.start_date.strftime('%v') %>
              </div>

              <div class="col-md-2">
                <%= link_to room_path(reservation.room) do %>
                  <%= image_tag reservation.room.cover_photo(:thumb) %>
                <% end %>
              </div>

              <div class="col-md-5">
                <%= link_to reservation.room.listing_name, room_path(reservation.room) %><br/><br/>
                <span>
                      <%= link_to user_path(reservation.user) do %>
                        <%= image_tag avatar_url(reservation.user), class: "img-circle avatar-small" %>
                    <%= reservation.user.fullname %>
                      <% end %>
                    </span>
              </div>
              <div class="col-md-3 text-right">
                <%= render partial: "reviews/host_form", locals: {reservation: reservation} %>
              </div>
            </div>
            <hr/>

          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link " %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link " %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>

    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

        <% @trips.each do |trip| %>
          <div class="row">
            <div class="col-md-2">
              <%= trip.start_date.strftime('%v') %>
            </div>

            <div class="col-md-2">
              <%= link_to room_path(trip.room) do %>
                <%= image_tag trip.room.cover_photo(:thumb) %>
              <% end %>
            </div>

            <div class="col-md-5">
              <%= link_to trip.room.listing_name, room_path(trip.room) %><br/><br/>
              <span>
                <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                <%= link_to user_path(trip.room.user) do %>
                  <% trip.room.user.fullname %>
                <% end %>
              </span>
            </div>

            <div class="com-md-3">
              <%= render partial: "reviews/guest_form", locals: {reservation: trip} %>
            </div>

          </div>
          <hr/>
        <% end %>


      </div>
    </div>
  </div>
</div>