config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?


  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "chiquita-minions-smiling-bob.jpg"
    end
  end


  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end




end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only:[:pricing,:description,:photo_upload,:amenities,:location,:update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved!"
    else
      flash[:alert] = "Something went wrong..."
      render 'rooms/new'
    end
  end

  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room
    if @room.update(new_params)
      flash[:notice] = 'Saved!'
    else
      flash[:alert] = 'Something went wrong.'
    end
      redirect_back(fallback_location: request.referer)
  end


  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today,today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
        conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end




  private

    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type,:room_type,:accomodate,:bed_room,:bath_room,:listing_name,:summary,:address,:is_tv,:is_kitchen,:is_air,:is_heating,:is_wifi,:price,:active)
    end

    def is_authorised
      redirect_to root_path, alert: 'You do not have the permission' unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.photos.blank? && !@room.listing_name.blank? && !@room.address.blank?
    end



end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag room.cover_photo(:medium) %>
      </div>
      <div class="panel-body">
        <%= link_to room.listing_name, room %><br/>
        $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
        <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
      </div>
    </div>
  </div>
  <script>
      $('#star_<%= room.id %>').raty({
          path: '/assets/',
          readOnly: true,
          score: <%= room.average_rating %>
      });
  </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_tv %> TV
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_kitchen %> Kitchen
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_wifi %> Internet
              </div>
            </div>

            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_heating %> Heating
              </div>
              <div class="col-md-4">
                <%= f.check_box :is_air %> Air Conditioning
              </div>
            </div>
            <br/><br/>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Description
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: 'What is your listing name?', class:'form-control', required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: 'Summary of your house', class:'form-control', required: true %>
              </div>
            </div>



            <div class="text-center">
              <%= f.submit 'Save', class:'btn btn-form' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active " %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link " %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link " %></li>

    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

          <% @rooms.each do |room| %>
            <div class="row">
              <div class="col-md-2">
                <%= image_tag room.cover_photo(:thumb) %>
              </div>
              <div class="col-md-7">
                <h4><%= link_to room.listing_name, room_path(room) %></h4>
              </div>
              <div class="col-md-3 right">
                <%= link_to "Update", listing_room_path(room) ,class: "btn btn-form"%>
              </div>
            </div>
            <hr/>
          <% end %>


      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Home Type</label>
                  <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                               id: "home_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Room Type</label>
                  <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                               id: "room_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Accommodate</label>
                  <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                               id: "accomodate", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bedrooms</label>
                  <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                               id: "bed_room", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bathrooms</label>
                  <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                               id: "bath_rooms", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

            </div>

            <div><%= f.submit "Save", class: "btn btn-normal" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Location
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Location</label>
                <%= f.text_field :address, placeholder: 'Where is your house?', class:'form-control', required: true  %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit 'Save', class:'btn btn-form' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room do |f| %>
        <div class="row">



          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [['Apartment', 'Apartment'], ['House', 'House'], ['Bed & Breakfast', 'Bed & Breakfast']],
                            id: 'home_type', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>


          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [['Entire', 'Entire'], ['Private', 'Private'], ['Shared', 'Shared']],
                           id: 'room_type', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>


          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accomodate</label>
              <%= f.select :accomodate, [['1', 1], ['2', 2], ['3', 3], ['4+', 4]],
                           id: 'accomodate', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>



          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [['1', 1], ['2', 2], ['3', 3], ['4+', 4]],
                           id: 'bed_room', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [['1', 1], ['2', 2], ['3', 3], ['4+', 4]],
                           id: 'bathroom', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>


        </div>

        <div><%= f.submit 'Create My Room', class: 'btn btn-normal' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>

  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Photo
      </div>


      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">


              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i>
                      Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

            <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Price</label>
                <%= f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover_photo(nil), width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @room.listing_name %></h1>
        <%= @room.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large" %><br/><br/>
        <%= @room.user.fullname %>
      </div>
    </div>
    <hr/>

    <!-- Room Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @room.home_type %></div>
        <div class="col-md-3"><%= pluralize(@room.accomodate, "Guest") %></div>
        <div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
        <div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @room.summary %></p>
      </div>
    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4>Amenities</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_wifi %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
            </ul>
          </div>

        </div>
      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
              <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
              <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                <%= image_tag photo.image.url() %>
              </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3>
          <%= pluralize(@guest_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div><%= render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row">

      <div id="map" style="width: 100%; height: 400px"></div>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZKgA0bVKnxSYVacqJ9oZDRCAmtbCxcCw"></script>
      <script>
          function initialize() {
              var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
              var map = new google.maps.Map(document.getElementById('map'), {
                  center: location,
                  zoom: 14
              });

              var marker = new google.maps.Marker({
                  position: location,
                  map: map
              });

              var infoWindow = new google.maps.InfoWindow({
                  content: '<div id="content"><%= image_tag @room.cover_photo(:medium) %></div>'
              });

              infoWindow.open(map, marker);
          }

          google.maps.event.addDomListener(window, 'load', initialize);
      </script>

    </div>
    <hr/>

    <!-- NEAR BY ROOMS -->
    <div class="row">
      <h3>Near by</h3>
      <% for room in @room.nearbys(10) %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.cover_photo(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room %><br/>
              (<%= room.distance.round(2) %> kms away)
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>


  <!-- RIGHT PANEL -->
  <div class="col-md-4">
    <!-- Reservation Form -->
    <%= render 'reservations/form' %>
  </div>
</div>

<script>
    $('#average_rating').raty({
        path: '/assets',
        readOnly: true,
        score: <%= @room.average_rating %>
    });
</script>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>