config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :destroy]
  end
  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, :styles => { :medium => "100x100#", :thumb => "50x50#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img)
      end

      @photos = @room.photos
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
  end


  def destroy
    @photo = Photo.find(params[:id])
    @room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: @room.id)

    respond_to :js
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")

<% if @room.photos.blank? %>
  $('#photo_check').hide();
<% end %>

<% if !@room.active && !@room.price.blank? && !@room.photos.blank? && !@room.listing_name.blank? && !@room.address.blank? %>
  $('#publish_button').attr('disabled',false);
<% else %>
  $('#publish_button').attr('disabled',true);

<% end %>